[tool.poetry]
name = "rrfit"
version = "0.1.0"
description = ""
authors = ["T1-Team <deleonlab@princeton.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
